# Generated by Django 4.0.4 on 2022-05-07 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_alter_message_date_sent_alter_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 7, 18, 31, 39, 168478)),
        ),
    ]
