# Generated by Django 4.0.4 on 2022-05-11 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0019_alter_message_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_bid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 11, 1, 20, 13, 590636)),
        ),
    ]
