# Generated by Django 4.0.4 on 2022-05-11 01:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0027_alter_bid_bid_posted'),
        ('message', '0020_message_is_bid_alter_message_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='bid_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_id', to='bid.bid'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 11, 1, 51, 0, 685349)),
        ),
    ]
