# Generated by Django 4.0.4 on 2022-05-13 01:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_card_nr_alter_payment_cvc_nr_and_more'),
        ('message', '0027_alter_message_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 13, 1, 7, 24, 268946)),
        ),
    ]
