# Generated by Django 4.0.4 on 2022-05-06 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='default-item.jpg', upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 6, 22, 13, 46, 250227)),
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
    ]
