# Generated by Django 4.0.4 on 2022-05-07 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_item_image_alter_item_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 7, 4, 30, 41, 78973)),
        ),
    ]
