# Generated by Django 4.0.4 on 2022-05-07 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_alter_item_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 7, 18, 31, 39, 167485)),
        ),
    ]
