# Generated by Django 4.0.4 on 2022-05-10 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_alter_item_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('1', 'Furniture'), ('2', 'Appliances'), ('3', 'Electronics')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 10, 14, 39, 31, 553898)),
        ),
    ]
