# Generated by Django 4.0.4 on 2022-05-10 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_alter_item_category_alter_item_date_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Furniture', 'Furniture'), ('Appliances', 'Appliances'), ('Electronics', 'Electronics')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 10, 15, 16, 18, 254707)),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(to='item.category'),
        ),
    ]
