# Generated by Django 4.0.4 on 2022-05-10 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_category_remove_item_category_alter_item_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 10, 15, 17, 46, 750592)),
        ),
    ]
