# Generated by Django 4.0.4 on 2022-05-10 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_alter_item_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Furniture', 'Furniture'), ('Appliances', 'Appliances'), ('Electronics', 'Electronics')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 10, 15, 23, 44, 501835)),
        ),
    ]
