# Generated by Django 4.0.4 on 2022-05-10 18:17

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0022_alter_item_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Furniture', 'Furniture'), ('Appliances', 'Appliances'), ('Electronics', 'Electronics')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 10, 18, 17, 25, 155919)),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
