# Generated by Django 4.0.4 on 2022-05-10 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_remove_item_category_item_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 10, 22, 8, 27, 909892)),
        ),
    ]
