# Generated by Django 4.0.4 on 2022-05-13 10:29

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0034_alter_item_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Furniture', 'Furniture'), ('Appliances', 'Appliances'), ('Electronics', 'Electronics'), ('Computers', 'Computers'), ('Pets', 'Pets'), ("Men's Clothing", 'Mens Clothing'), ("Women's Clothing", 'Womens Clothing'), ('Vehicles', 'Vehicles'), ('Cars', 'Cars'), ('Bikes', 'Bikes'), ('Instruments', 'Instruments'), ('Toys', 'Toys'), ('Books', 'Books'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=134, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 13, 10, 29, 27, 489923)),
        ),
    ]
