# Generated by Django 4.0.4 on 2022-05-07 18:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0012_alter_item_date_posted'),
        ('bid', '0002_bids_bid_amount_alter_bids_bid_posted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField()),
                ('bid_posted', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 7, 18, 27, 6, 697026))),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Bids',
        ),
    ]
