# Generated by Django 4.0.4 on 2022-05-11 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0024_alter_bid_bid_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 11, 1, 1, 6, 721828)),
        ),
    ]
