# Generated by Django 4.0.4 on 2022-05-11 21:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0028_alter_bid_bid_posted_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 11, 21, 36, 33, 627482)),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
