# Generated by Django 4.0.4 on 2022-05-12 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0031_alter_bid_bid_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 12, 4, 35, 9, 529217)),
        ),
    ]
